# -*- coding: utf-8 -*-
"""内置数据源定义"""

BUILTIN_DATA_SOURCES = [
    {'key': 'google-drive', 'name': 'Google Drive', 'icon': '📂', 'bg': '#E8FFEA', 'desc': 'Google Drive 数据源',
     'author': 'langgenius', 'downloads': '58,605', 'tags': ['RAG'],
     'fields': [{'key': 'token', 'label': '访问令牌', 'placeholder': 'Google OAuth Access Token', 'required': True}]},
    {'key': 'gitlab', 'name': 'GitLab', 'icon': '🦊', 'bg': '#FFF0E8', 'desc': 'GitLab 项目数据源 - 访问项目、问题、合并请求和文件',
     'author': 'langgenius', 'downloads': '85,960', 'tags': ['RAG'],
     'fields': [{'key': 'token', 'label': '个人访问令牌', 'placeholder': 'GitLab Personal Access Token', 'required': True}]},
    {'key': 'firecrawl', 'name': 'Firecrawl', 'icon': '🔥', 'bg': '#FFECE8', 'desc': 'Firecrawl Datasource',
     'author': 'langgenius', 'downloads': '74,254', 'tags': ['RAG'],
     'fields': [{'key': 'api_key', 'label': 'API 密钥', 'placeholder': 'Firecrawl API Key', 'required': True}]},
    {'key': 'notion', 'name': 'Notion', 'icon': '📝', 'bg': '#F2F3F5', 'desc': 'Notion Datasource',
     'author': 'langgenius', 'downloads': '71,494', 'tags': ['RAG'],
     'fields': [{'key': 'token', 'label': '内部集成令牌', 'placeholder': 'Notion Internal Integration Token', 'required': True}]},
    {'key': 'jina-reader', 'name': 'Jina Reader', 'icon': '📖', 'bg': '#E8F7FF', 'desc': 'Jina Reader Datasource',
     'author': 'langgenius', 'downloads': '53,282', 'tags': ['RAG'],
     'fields': [{'key': 'api_key', 'label': 'API 密钥', 'placeholder': 'Jina Reader API Key（可留空）', 'required': False}]},
    {'key': 'github', 'name': 'GitHub', 'icon': '🐙', 'bg': '#F2F3F5', 'desc': 'GitHub 仓库数据源 - 访问仓库、问题、拉取请求和 Wiki 页面',
     'author': 'langgenius', 'downloads': '19,081', 'tags': ['RAG'],
     'fields': [{'key': 'token', 'label': '个人访问令牌', 'placeholder': 'GitHub Personal Access Token', 'required': True}]},
    {'key': 'sharepoint', 'name': 'SharePoint', 'icon': '🔷', 'bg': '#E8F7FF', 'desc': 'SharePoint 数据源',
     'author': 'langgenius', 'downloads': '10,795', 'tags': ['RAG'],
     'fields': [{'key': 'tenant_id', 'label': '租户 ID', 'placeholder': 'Azure AD Tenant ID', 'required': True},
                {'key': 'client_id', 'label': '客户端 ID', 'placeholder': 'Azure AD Client ID', 'required': True},
                {'key': 'client_secret', 'label': '客户端密钥', 'placeholder': 'Azure AD Client Secret', 'required': True}]},
    {'key': 'confluence', 'name': 'Confluence', 'icon': '💠', 'bg': '#EAF1FE', 'desc': 'Confluence Datasource',
     'author': 'langgenius', 'downloads': '9,734', 'tags': ['RAG'],
     'fields': [{'key': 'token', 'label': '个人访问令牌', 'placeholder': 'Confluence Personal Access Token', 'required': True}]},
    {'key': 'tavily', 'name': 'Tavily', 'icon': '🔎', 'bg': '#F5E8FF', 'desc': 'Tavily 搜索提取数据源',
     'author': 'langgenius', 'downloads': '9,442', 'tags': ['RAG'],
     'fields': [{'key': 'api_key', 'label': 'API 密钥', 'placeholder': 'Tavily API Key', 'required': True}]},
    {'key': 'onedrive', 'name': 'OneDrive', 'icon': '☁️', 'bg': '#E8F7FF', 'desc': 'OneDrive 数据源',
     'author': 'langgenius', 'downloads': '8,018', 'tags': ['RAG'],
     'fields': [{'key': 'token', 'label': '访问令牌', 'placeholder': 'Microsoft OAuth Access Token', 'required': True}]},
    {'key': 'aws-s3', 'name': 'AWS S3 Storage', 'icon': '🪣', 'bg': '#E8FFEA', 'desc': 'AWS S3 Storage 数据源',
     'author': 'langgenius', 'downloads': '5,117', 'tags': ['RAG'],
     'fields': [{'key': 'access_key_id', 'label': 'Access Key ID', 'placeholder': 'AWS Access Key ID', 'required': True},
                {'key': 'secret_access_key', 'label': 'Secret Access Key', 'placeholder': 'AWS Secret Access Key', 'required': True},
                {'key': 'bucket_region', 'label': '存储桶区域', 'placeholder': '例如 us-east-1', 'required': True},
                {'key': 'bucket_name', 'label': '存储桶名称', 'placeholder': '例如 my-bucket', 'required': True}]},
    {'key': 'tencent-cos', 'name': '腾讯云 COS 存储', 'icon': '🌐', 'bg': '#EAF1FE', 'desc': '腾讯云 COS 存储数据源',
     'author': 'langgenius', 'downloads': '3,481', 'tags': ['RAG'],
     'fields': [{'key': 'secret_id', 'label': 'SecretId', 'placeholder': '腾讯云 SecretId', 'required': True},
                {'key': 'secret_key', 'label': 'SecretKey', 'placeholder': '腾讯云 SecretKey', 'required': True},
                {'key': 'bucket', 'label': '存储桶', 'placeholder': '例如 my-bucket-1250000000', 'required': True},
                {'key': 'region', 'label': '地域', 'placeholder': '例如 ap-guangzhou', 'required': True}]},
]
